### PR TITLE
feat: add a position listener

### PR DESCRIPTION
**Pull request by christophemacabiau**
Hi,
Following the [discussion](https://github.com/fleaflet/flutter_map/pull/719#issuecomment-690469261) on your PR, a first implementation based on your branch. Tell me what you think.

### CODE REVIEW

**Comment by christophemacabiau** [comment]
I didn't found any way to remove this fake sequence of scaleStart-scaleUpdate-scaleEnd after a pinch...

**Comment by maRci002** [comment]
I'll check it out soon, I don't know why didn't notify github about this PR.

**Comment by maRci002** [comment]
I think this feature would be too much for this issue (gesture race implementation was overkill too). I am going to remove the WIP flag from the title soon (I still need to recheck the code and add some docs) and when it is merged into master then you can create a direct PR to [flutter_map](https://github.com/fleaflet/flutter_map) repository.

Anyway that number `5` seems [magic number](https://en.wikipedia.org/wiki/Magic_number_(programming)) for me. This feature is a special request which is good but maybe there is a cleaner solution and more generics one which would handle other cases, I know currently this solves you problem and thats good. Don't forget you can keep and test a local copy of the project and maintain it. Forinstance I have a lot of private code which wasn't allowed to push into flutter_map's private repo and in the very close future I think I have to implement something like this so I can help if it is allowed.

**Comment by christophemacabiau** [comment]
Sorry for the delay. Thanks for your answer.
The flutter_map does not seem to be very active... I will use my fork for the moment.

**Pull request closed without merging**
